### ISSUE TITLE
kube2sky fails to connect to api server

### ISSUE THREAD

**Issue by raffaelespazzoli** [justingrayston/kubernetes-docker-dns#13]
hi, I followed the tutorial step by step. 
I made just made the following change: 
export KUBE_SERVER=http:\/\/10.0.2.15:8080 
to the config.sh file.
10.0.2.15 is the ip of my virtualbox centos instance where I'm running this example.

when I start the dns, the cube2sky container fails with the following:

I1210 14:58:54.953923       1 kube2sky.go:455] Using http://10.0.2.15:8080 for kubernetes master
I1210 14:58:54.953942       1 kube2sky.go:456] Using kubernetes API v1
E1210 14:58:55.958253       1 reflector.go:136] Failed to list *api.Service: Get http://10.0.2.15:8080/api/v1/services: dial tcp 10.0.2.15:8080: no route to host

the error message suggest that the cube2sky container network interface cannot reach 10.0.2.15.
as far as I understand, because we are using a local cluster we don't need to setup a proper kubernetes networking configuration, but we can simply rely on what docker provides.
So what we need to make sure is that docker containers can communicate with the docker host.
how do I do that? can you help?

some additional info
docker exec 259d73f46b92 ping -w3 10.0.2.15
where 259d73f46b92 is the kube2sky container. 
this works, but:
[osboxes@osboxes ~]$ docker exec 259d73f46b92 telnet 10.0.2.15 8080
telnet: can't connect to remote host (10.0.2.15): No route to host

so maybe the no route to host message is misleading, it looks more like the 8080 port is blocked. why would that be?

if I issue the command on my docker host:
netstat -a | grep webcache | grep LISTEN
where webcache is  8080 I get
tcp6       0      0 [::]:webcache           [::]:\*                  LISTEN 

so it looks like only tcp6 is listening on 8080, how is that possible?

the following command on my docker host: 
curl http://10.0.2.15:8080
works. This, I guess, does not use tcp6....

**Comment by justingrayston** [comment]
So 10.0.2.15 is the assigned IP of the virtual box on the host machine? As stated in the docs this was done so the team which mostly have Macs could run a system as identical as production as possible, so I haven't done test on linux.

#9 was also on linux, and you can see that the docker host IP is in a completely different range and that is what resolved the issue. 

If this is your host network IP, then perhaps it is clashing with some of the ranges kubernetes works with?  For example some IPs are reserved for services. 

https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/services.md#virtual-ips-and-service-proxies

Long shot that you have a conflict but would explain why the IP can't reach the host network. 

If this was the IP of the kube master itself then 

```
the following command on my docker host: 
curl http://10.0.2.15:8080
```

would work from the docker host because you will be accessing the container.

Then again why couldn't the other container?? 

In the docker host, what is the output of `ifconfig`?

**Comment by raffaelespazzoli** [comment]
I had firewalld on.
once I turned it off, it started working....

I'll do penance :)
thanks.

**Comment by justingrayston** [comment]
Ha! No probs :D
